### ISSUE TITLE
Making sure Caddy 2 can handle the proxyprotocol plugin

### ISSUE THREAD

**Issue by mholt** [mastercactapus/proxyprotocol#2]
Hi Nathaniel, hope all is well! This is not an issue that needs you to do anything, really. It's more for discussion, and it's totally optional. I am just looking at making sure Caddy 2 will be able to support the PROXY protocol, likely via a plugin (called a "module" in Caddy 2).

In Caddy 2, listeners are [configured simply by giving a list of addresses](https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httpservers), as strings: `"listen": ["localhost:5000", "localhost:8080"]` for example.

I think this concise format is pretty useful for the majority of use cases, but it makes it hard to define listeners which need custom behavior at the network level (as opposed to the HTTP or application level). Clearly we need to support listener "middleware" like we do in v1.

So I was thinking of a new property called `listen_advanced` (or something) that allows one to define a listener with custom/modular behavior:

```json
{
    "listen_advanced": {
        "addresses": ["localhost:5000",  "localhost:8080"],
        "modules": [
            {
                "listener_module": "proxy_protocol",
                "other": "config goes here"
            }
        ]
    }
}
```

Anyway, just thought I'd check with you if you had any opinions on the matter, or requests for a v2 way of doing this. If it sounds good to you, feel free to just let me know and close this issue, thanks!

**Comment by SteffenDE** [comment]
I guess this can be closed now? (https://github.com/mastercactapus/caddy-proxyprotocol/issues/9)
