### ISSUE TITLE
"Invalid source address" when proxy header contains IPv4-mapped IPv6 address

### ISSUE THREAD

**Issue by jtackaberry** [mastercactapus/proxyprotocol#5]
I encountered this using caddy-l4 which depends on this project.  I opened https://github.com/mholt/caddy-l4/issues/91 but later realized I should open an issue here.

Consider the following proxy protocol header (which is passed by haproxy in my environment):

```
PROXY TCP6 ::ffff:192.168.0.1 ::ffff:192.168.0.1 53740 10001
```

Given this header, parseV1() returns the error "invalid source address."  The reason seems to be [this line](https://github.com/mastercactapus/proxyprotocol/blob/788199c12597ba333bc5f6477ab5c750503b46eb/headerv1.go#L76) because net.IP.To4() will return non-nil when ParseIP() parses a v4-mapped IPv6 address.

**Comment by mastercactapus** [comment]
Fixed in v0.0.4, added a test for good measure with that input: https://github.com/mastercactapus/proxyprotocol/commit/ab99c61acf16026043e36f5d4d862596386a0372#diff-e93e273b358f8a3fef526e6a690d82f02dd3cf59d40fb654d350acdad8062991R69
